spring:
  profiles:
    include: oauth
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb;MODE=MYSQL
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    show-sql: true
    properties:
      format_sql: true
      hibernate:
        storage_engine: innodb
        globally_quoted_identifiers: true

server:
  servlet:
    encoding:
      force-response: true